### ISSUE TITLE
Remove error on duplicated selection?

### ISSUE THREAD

**Issue by etiennebacher** [pola-rs/r-polars#266]
Should `select()` allow duplicated names in selection to avoid this kind of error?

``` r
library(polars)
pl$DataFrame(a = 1:3)$select("a", "a")
#> Error: when calling $collect() on LazyFrame:
#> Duplicate(ErrString("column with name 'a' has more than one occurrences"))
#>  [TRUNCATED]
```

**Comment by sorhawell** [comment]
The same error will pop up in `py-polars`, as it is not one cannot `select` the same column twice, but it is not allowed to output columns with same name.

```python
>>> import polars as pl
>>> pl.DataFrame({"a":[1,2,3]}).select("a","a")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.10/site-packages/polars/dataframe/frame.py", line 7089, in select
    return self.lazy().select(*exprs, **named_exprs).collect(no_optimization=True)
  File "/usr/local/lib/python3.10/site-packages/polars/lazyframe/frame.py", line 1512, in collect
    return wrap_df(ldf.collect())
exceptions.DuplicateError: column with name 'a' has more than one occurrences

>>> pl.DataFrame({"a":[1,2,3]}).select("a",pl.col("a").suffix("_2"))
shape: (3, 2)
┌─────┬─────┐
│ a   ┆ a_2 │
│ --- ┆ --- │
│ i64 ┆ i64 │
╞═════╪═════╡
│ 1   ┆ 1   │
│ 2   ┆ 2   │
│ 3   ┆ 3   │
└─────┴─────┘
```

```R
> pl$DataFrame(a=1:3)$select("a",pl$col("a")$suffix("_2"))
shape: (3, 2)
┌─────┬─────┐
│ a   ┆ a_2 │
│ --- ┆ --- │
│ i32 ┆ i32 │
╞═════╪═════╡
│ 1   ┆ 1   │
│ 2   ┆ 2   │
│ 3   ┆ 3   │
└─────┴─────┘
```

**Comment by etiennebacher** [comment]
This makes sense, thank you
