### ISSUE TITLE
Running twice some code that panicks generates a segfault

### ISSUE THREAD

**Issue by etiennebacher** [pola-rs/r-polars#734]
Slightly related to #733 

```r
library(polars)
pl$DataFrame(mtcars)$sort("cyl", descending = NULL)
pl$DataFrame(mtcars)$sort("cyl", descending = NULL)
```
````
This reprex appears to crash R.
See standard output and standard error for more details.

#### Standard output and error

``` sh
thread '<unnamed>' panicked at C:\Users\etienne\.cargo\git\checkouts\polars-b0d90607192fd414\fa59ffc\crates\polars-core\src\frame\mod.rs:1798:42:
index out of bounds: the len is 0 but the index is 0
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread '<unnamed>' panicked at C:\Users\etienne\.cargo\git\checkouts\polars-b0d90607192fd414\fa59ffc\crates\polars-core\src\frame\mod.rs:1798:42:
index out of bounds: the len is 0 but the index is 0
thread '<unnamed>' panicked at src\lazy\dataframe.rs:43:1:
explicit panic
thread '<unnamed>' panicked at C:\Users\etienne\.cargo\git\checkouts\extendr-569c02e1a164cdf5\b26adfe\extendr-api\src\thread_safety.rs:59:49:
called `Result::unwrap()` on an `Err` value: NulError(31, [117, 115, 101, 114, 32, 102, 117, 110, 99, 116, 105, 111, 110, 32, 112, 97, 110, 105, 99, 107, 101, 100, 58, 32, 99, 111, 108, 108, 101, 99, 116, 0])
fatal runtime error: failed to initiate panic, error 5
```
````

**Comment by ssh352** [comment]
```
> library(polars)
> pl$DataFrame(mtcars)$sort("cyl", descending = NULL)
thread '<unnamed>' panicked at /Users/test/.cargo/git/checkouts/polars-b0d90607192fd414/fa59ffc/crates/polars-core/src/frame/mod.rs:1798:42:
index out of bounds: the len is 0 but the index is 0
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
polars: closing concurrent R handler
Error: Execution halted with the following contexts
   0: In R: in $collect():
   0: During function call [pl$DataFrame(mtcars)$sort("cyl", descending = NULL)]
   1: A polars sub-thread panicked. See panic msg, which is likely more informative than this error: Any { .. }
> sessionInfo()
R version 4.3.2 (2023-10-31)
Platform: x86_64-apple-darwin20 (64-bit)
Running under: macOS Ventura 13.6.3
```
it actually crashes the first run with polars_0.12.2.9000 on MacOS
