### ISSUE TITLE
Using literals in `$agg()` doesn't match the python behavior

### ISSUE THREAD

**Issue by etiennebacher** [pola-rs/r-polars#797]
Mentioned in #796

```
pl$DataFrame(a = c(1, 1, 2, 2, 2, 3, 3, 3))$
  group_by("a")$
  agg(x = c(1, 2, 3, 4))

shape: (3, 2)
┌─────┬─────┐
│ a   ┆ x   │
│ --- ┆ --- │
│ f64 ┆ f64 │
╞═════╪═════╡
│ 2.0 ┆ 1.0 │
│ 1.0 ┆ 1.0 │
│ 3.0 ┆ 1.0 │
└─────┴─────┘
```

```
import polars as pl
pl.DataFrame({"a": [1, 1, 2, 2, 2, 3, 3, 3]}).group_by("a").agg(x=[1, 2, 3, 4])

shape: (3, 2)
┌─────┬─────────────┐
│ a   ┆ x           │
│ --- ┆ ---         │
│ i64 ┆ list[i64]   │
╞═════╪═════════════╡
│ 2   ┆ [1, 2, … 4] │
│ 3   ┆ [1, 2, … 4] │
│ 1   ┆ [1, 2, … 4] │
└─────┴─────────────┘
```

**Comment by etiennebacher** [comment]
I'm stuck here. I tried to track down this quite deep on the Rust side, but AFAICT the literal `pl$lit(c(1, 2, 3, 4))` is correctly converted to a float32 Series ([as expected](https://docs.pola.rs/py-polars/html/reference/expressions/api/polars.lit.html#polars.lit)) so I just don't know why this fails.

**Comment by etiennebacher** [comment]
Even simpler reprex:

```r
> pl$DataFrame(x = c(1, 2, 3))$with_columns(foo = c(4, 5, 6, 7))
Error: Execution halted with the following contexts
   0: In R: in $with_columns()
   0: During function call [pl$DataFrame(x = c(1, 2, 3))$with_columns(foo = c(4, 5, 6, 7))]
   1: Encountered the following error in Rust-Polars:
      	lengths don't match: unable to add a column of length 4 to a DataFrame of height 3
```

```python
>>> pl.DataFrame({"x": [1, 2, 3]}).with_columns(foo=[4, 5, 6, 7])
shape: (3, 2)        
┌─────┬─────────────┐
│ x   ┆ foo         │
│ --- ┆ ---         │
│ i64 ┆ list[i64]   │
╞═════╪═════════════╡
│ 1   ┆ [4, 5, … 7] │
│ 2   ┆ [4, 5, … 7] │
│ 3   ┆ [4, 5, … 7] │
└─────┴─────────────┘
```

**Comment by eitsupi** [comment]
This may be explained by the difference between Python type mapping and R type mapping.
That is, if you try to assign a Series of height 4 to a DataFrame of height 3 in Python, as shown below, you will get an error.

```python
>>> import polars as pl
>>> pl.DataFrame({"x": [1, 2, 3]}).with_columns(foo=pl.Series(values = [4, 5, 6, 7]))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/rstudio/.local/lib/python3.10/site-packages/polars/dataframe/frame.py", line 8302, in with_columns
    return self.lazy().with_columns(*exprs, **named_exprs).collect(_eager=True)
  File "/home/rstudio/.local/lib/python3.10/site-packages/polars/lazyframe/frame.py", line 1937, in collect
    return wrap_df(ldf.collect())
polars.exceptions.ShapeError: unable to add a column of length 4 to a DataFrame of height 3
```

In R, it is natural to expect the same error because the strategy is such that vectors of length 4 are converted as much as possible to Series of length 4.

Perhaps the problem here is the following conversion.

```r
> as_polars_series(list(4, 5, 6, 7))
polars Series: shape: (4,)
Series: '' [list[f64]]
[
        [4.0]
        [5.0]
        [6.0]
        [7.0]
]

> as_polars_series(list(list(4, 5, 6, 7)))
polars Series: shape: (1,)
Series: '' [list[list[f64]]]
[
        [[4.0], [5.0], … [7.0]]
]
```

**Comment by eitsupi** [comment]
```python
>>> import polars as pl
>>> pl.select(pl.lit([4, 5, 6, 7]))
shape: (1, 1)
┌─────────────┐
│ literal     │
│ ---         │
│ list[i64]   │
╞═════════════╡
│ [4, 5, … 7] │
└─────────────┘
```

```r
> library(polars)
> pl$select(pl$lit(4L:7L))
shape: (4, 1)
┌─────┐
│     │
│ --- │
│ i32 │
╞═════╡
│ 4   │
│ 5   │
│ 6   │
│ 7   │
└─────┘
> pl$select(pl$lit(list(4L:7L)))
shape: (1, 1)
┌─────────────┐
│             │
│ ---         │
│ list[i32]   │
╞═════════════╡
│ [4, 5, … 7] │
└─────────────┘
```

**Comment by etiennebacher** [comment]
Yes also confirmed for `$agg()`:

```r
pl$DataFrame(a = c(1, 1, 2, 2, 2, 3, 3, 3))$
    group_by("a")$
    agg(x = list(c(1, 2, 3, 4)))

shape: (3, 2)
┌─────┬───────────────────┐
│ a   ┆ x                 │
│ --- ┆ ---               │
│ f64 ┆ list[f64]         │
╞═════╪═══════════════════╡
│ 3.0 ┆ [1.0, 2.0, … 4.0] │
│ 2.0 ┆ [1.0, 2.0, … 4.0] │
│ 1.0 ┆ [1.0, 2.0, … 4.0] │
└─────┴───────────────────┘
```
I'll add a test for this and then we can close this
